'use client'
import StyledComponentsRegistry from '@/styles'
import { defaultTheme } from '@/styles/defaultTheme'
import { Roboto } from 'next/font/google'
import { ThemeProvider } from 'styled-components'
import { GlobalStyle } from './globalStyles'
import Header from '@/components/header'
import { Container } from '@/styles/container'
import React from 'react'
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })
export const metadata = {
  title: 'Shopify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <ThemeProvider theme={defaultTheme}>
            <Container>
              <Header />
              {children}
            </Container>
            <GlobalStyle />
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
